"""
Orchestrates: noisy OCR text -> clean medicine name/composition -> ban-status
lookup (vector DB first, live web search fallback) -> final structured answer.
"""

import json
import ast
import re
from decouple import config
from google import genai
from google.genai import types

from vector_store import search_banned_db

GEMINI_MODEL = config("GEMINI_MODEL", default="gemini-3.5-flash")
ENABLE_WEB_SEARCH = config("ENABLE_WEB_SEARCH", default=False, cast=bool)
ENABLE_LLM_IDENTITY = config("ENABLE_LLM_IDENTITY", default=False, cast=bool)
ENABLE_LLM_SUMMARY = config("ENABLE_LLM_SUMMARY", default=False, cast=bool)

_client = None

DISCLAIMER = (
    "This information is generated by an AI system and may be incomplete or "
    "inaccurate. It is not medical advice. Always consult a licensed medical "
    "practitioner or pharmacist before taking, stopping, or making any "
    "decisions about a medicine."
)


def _get_client():
    global _client
    if _client is None:
        _client = genai.Client(api_key=config("GEMINI_API_KEY"))
    return _client


def _clean_loose_value(value: str):
    value = value.strip().rstrip(",").strip()
    lower_value = value.lower()

    if lower_value in {"none", "null"}:
        return None
    if lower_value == "true":
        return True
    if lower_value == "false":
        return False

    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    elif value.startswith(("'", '"')):
        value = value[1:]
    elif value.endswith(("'", '"')):
        value = value[:-1]

    return " ".join(value.split())


def _parse_loose_object(text: str) -> dict:
    """Parse imperfect model dicts such as single quotes or broken strings."""
    start = text.find("{")
    end = text.rfind("}")
    body = text[start + 1 : end] if start != -1 and end != -1 and end > start else text

    pattern = re.compile(
        r"""["']?([A-Za-z_][A-Za-z0-9_]*)["']?\s*:\s*(.*?)"""
        r"""(?=,\s*["']?[A-Za-z_][A-Za-z0-9_]*["']?\s*:|\n\s*["']?[A-Za-z_][A-Za-z0-9_]*["']?\s*:|$)""",
        re.DOTALL,
    )
    parsed = {
        key: _clean_loose_value(value)
        for key, value in pattern.findall(body)
        if value.strip()
    }
    if not parsed:
        raise ValueError("Model response did not contain parseable key/value pairs")
    return parsed


def _parse_json_response(text: str) -> dict:
    """Parse a model JSON response, tolerating common markdown wrappers."""
    text = (text or "").strip()
    if not text:
        raise ValueError("Empty model response")

    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    start = text.find("{")
    end = text.rfind("}")
    json_text = text[start : end + 1] if start != -1 and end != -1 and end > start else text

    try:
        return json.loads(json_text)
    except json.JSONDecodeError:
        try:
            parsed = ast.literal_eval(json_text)
            if isinstance(parsed, dict):
                return parsed
        except (SyntaxError, ValueError):
            return _parse_loose_object(json_text)
        raise ValueError("Model response was not a JSON object")


def _clean_ocr_line(line: str) -> str:
    line = re.sub(r"[^A-Za-z0-9+/%().,\- ]+", " ", line)
    line = re.sub(r"\s+", " ", line).strip(" .,-")
    return line


def _is_noise_line(line: str) -> bool:
    lowered = line.lower()
    noise_terms = {
        "batch",
        "b.no",
        "mfg",
        "exp",
        "expiry",
        "mrp",
        "price",
        "license",
        "licence",
        "manufactured",
        "marketed",
        "address",
        "customer",
        "warning",
        "caution",
        "store",
        "temperature",
        "schedule",
        "dosage",
        "barcode",
    }
    if any(term in lowered for term in noise_terms):
        return True
    letters = sum(ch.isalpha() for ch in line)
    digits = sum(ch.isdigit() for ch in line)
    return letters < 3 or digits > letters * 2


def _identity_from_ocr_text(raw_ocr_text: str) -> dict:
    lines = [_clean_ocr_line(line) for line in raw_ocr_text.splitlines()]
    lines = [line for line in lines if line and not _is_noise_line(line)]
    normalized_text = _clean_ocr_line(raw_ocr_text)
    normalized_lower = normalized_text.lower()

    dolo_match = re.search(r"\b(?:d[o0]l[o0]|dpl[o0])[-\s]?(?:65[o0]|650|638)\b", normalized_lower)
    paracetamol_match = re.search(r"para\s*cetamol|paracetamol|p[a-z]{0,3}\s*facetamol", normalized_lower)
    dosage_match = re.search(r"\b(650|65o|500|50o)\s*mg\b", normalized_lower)

    if dolo_match or paracetamol_match:
        brand_name = "Dolo-650" if dolo_match else None
        dosage = "650 mg" if brand_name or (dosage_match and dosage_match.group(1).lower() in {"650", "65o"}) else None
        generic_name = "Paracetamol"
        if dosage:
            generic_name = f"{generic_name} {dosage}"
        search_query = " ".join(part for part in (brand_name, generic_name) if part)
        return {
            "brand_name": brand_name,
            "generic_name": generic_name,
            "search_query": search_query,
            "confidence": "high" if brand_name and paracetamol_match else "medium",
        }

    if not lines:
        return {
            "brand_name": None,
            "generic_name": None,
            "search_query": normalized_text[:200],
            "confidence": "low",
        }

    composition_terms = (
        "contains",
        "composition",
        "each",
        "equivalent",
        "paracetamol",
        "ibuprofen",
        "nimesulide",
        "metamizole",
        "dipyrone",
        "phenylpropanolamine",
    )
    generic_line = next(
        (line for line in lines if any(term in line.lower() for term in composition_terms)),
        None,
    )
    brand_line = next((line for line in lines if line != generic_line), lines[0])

    query_parts = []
    if brand_line:
        query_parts.append(brand_line)
    if generic_line and generic_line != brand_line:
        query_parts.append(generic_line)

    return {
        "brand_name": brand_line,
        "generic_name": generic_line,
        "search_query": " ".join(query_parts)[:200],
        "confidence": "medium" if brand_line else "low",
    }


def extract_medicine_identity(raw_ocr_text: str) -> dict:
    """Cleans noisy OCR text into a structured guess of medicine name + active
    ingredients, so we have a good query string for the vector DB / web search."""
    if not ENABLE_LLM_IDENTITY:
        return _identity_from_ocr_text(raw_ocr_text)

    prompt = f"""You are given messy OCR text extracted from the back of a medicine
strip/box. It may contain typos, broken words, batch numbers, dosage info, and
manufacturer details mixed in.

OCR TEXT:
---
{raw_ocr_text}
---

Return ONLY a JSON object (no markdown fences, no preamble) with this shape:
{{
  "brand_name": "<best guess of brand name, or null>",
  "generic_name": "<best guess of active ingredient(s)/generic/composition, or null>",
  "search_query": "<a short, clean search string combining the above, best for looking up ban status>",
  "confidence": "<high|medium|low>"
}}"""

    try:
        resp = _get_client().models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                max_output_tokens=400,
                response_mime_type="application/json",
            ),
        )
        return _parse_json_response(resp.text)
    except Exception as e:
        print(f"[llm] LLM identity extraction failed, using local OCR identity: {e}")
        return _identity_from_ocr_text(raw_ocr_text)


def _answer_from_best_db_match(identity: dict, matches: list[dict]) -> dict:
    best_match = matches[0] if matches else {}
    medicine_name = (
        best_match.get("name")
        or identity.get("brand_name")
        or identity.get("generic_name")
        or "Unknown"
    )
    banned_in = best_match.get("banned_in", [])
    restricted_in = best_match.get("restricted_in", [])

    restrictions = []
    if banned_in:
        restrictions.append(f"banned in {', '.join(banned_in)}")
    if restricted_in:
        restrictions.append(f"restricted in {', '.join(restricted_in)}")
    status = "; ".join(restrictions) if restrictions else "not flagged as banned in the local database"

    return {
        "medicine_name": medicine_name,
        "banned_in_india": "India" in banned_in,
        "banned_in_usa": "USA" in banned_in,
        "status_summary": f"{medicine_name} is {status}. {best_match.get('reason', '')}".strip(),
        "general_info": best_match.get("category", ""),
        "source": "internal_database",
    }


def _answer_from_vector_matches(identity: dict, matches: list[dict]) -> dict:
    if not ENABLE_LLM_SUMMARY:
        return _answer_from_best_db_match(identity, matches)

    prompt = f"""A user scanned a medicine. Extracted identity: {json.dumps(identity)}.

Our internal database found these potentially matching banned/restricted
medicine records:
{json.dumps(matches, indent=2)}

Using ONLY this data plus your general pharmacology knowledge for the "general
info" section, respond with ONLY a JSON object (no markdown fences):
{{
  "medicine_name": "<best identified name>",
  "banned_in_india": true|false,
  "banned_in_usa": true|false,
  "status_summary": "<1-2 sentence plain-language summary of ban/restriction status in India and USA>",
  "general_info": "<2-4 sentence general info on what this medicine/class is typically used for>",
  "source": "internal_database"
}}"""

    try:
        resp = _get_client().models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                max_output_tokens=500,
                response_mime_type="application/json",
            ),
        )
        return _parse_json_response(resp.text)
    except Exception as e:
        print(f"[llm] Vector-match summarization failed, using raw DB match: {e}")
        return _answer_from_best_db_match(identity, matches)


def _answer_without_web_search(identity: dict) -> dict:
    query = identity.get("search_query") or identity.get("brand_name") or identity.get("generic_name")
    return {
        "medicine_name": query or "Unknown",
        "banned_in_india": None,
        "banned_in_usa": None,
        "status_summary": (
            "No confident match was found in the local banned-medicines database. "
            "Live web search is disabled to avoid Gemini free-tier quota usage, so please verify manually."
        ),
        "general_info": "",
        "source": "local_database_no_match",
    }


def _answer_from_web_search(identity: dict) -> dict:
    """Fallback path: nothing in the vector DB cleared the similarity threshold,
    so ask Gemini to research it live using Google Search grounding."""
    query = identity.get("search_query") or identity.get("brand_name") or identity.get("generic_name")

    prompt = f"""Research whether the medicine "{query}" (brand: {identity.get('brand_name')},
generic/composition: {identity.get('generic_name')}) is banned or restricted in
India and/or the USA. Use web search to check current regulatory status
(CDSCO / Ministry of Health for India, FDA for USA).

After researching, respond with ONLY a JSON object as your final message (no
markdown fences, no extra commentary):
{{
  "medicine_name": "<best identified name>",
  "banned_in_india": true|false|null,
  "banned_in_usa": true|false|null,
  "status_summary": "<1-2 sentence plain-language summary, cite what you found>",
  "general_info": "<2-4 sentence general info on typical use>",
  "source": "web_search"
}}"""

    resp = _get_client().models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            max_output_tokens=1000,
            tools=[types.Tool(google_search=types.GoogleSearch())],
        ),
    )
    final_text = (resp.text or "{}").strip()

    try:
        return _parse_json_response(final_text)
    except json.JSONDecodeError:
        return {
            "medicine_name": query or "Unknown",
            "banned_in_india": None,
            "banned_in_usa": None,
            "status_summary": "Web search ran but the result could not be parsed reliably. Please verify manually.",
            "general_info": "",
            "source": "web_search",
        }


def analyze_medicine(raw_ocr_text: str) -> dict:
    """Full pipeline: identity extraction -> vector DB lookup -> web fallback."""
    identity = extract_medicine_identity(raw_ocr_text)
    query = identity.get("search_query") or raw_ocr_text[:200]

    matches = search_banned_db(query)

    if matches:
        result = _answer_from_vector_matches(identity, matches)
    elif ENABLE_WEB_SEARCH:
        try:
            result = _answer_from_web_search(identity)
        except Exception as e:
            print(f"[llm] Web search fallback failed: {e}")
            result = _answer_without_web_search(identity)
    else:
        result = _answer_without_web_search(identity)

    result["identity"] = identity
    result["disclaimer"] = DISCLAIMER
    return result
